# Generated by Django 6.1.1 on 2026-09-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
