# Generated by Django 6.1.1 on 2026-09-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place')),
            ],
        ),
    ]
