# Generated by Django 6.1.1 on 2026-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
    ]
