# Generated by Django 6.1.1 on 2026-10-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tbl_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_place',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.tbl_district'),
        ),
    ]
