# Generated by Django 6.1.1 on 2026-10-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_tbl_place_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_place',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district'),
        ),
    ]
